### ISSUE TITLE
Alerts - Storage Backend Status

### ISSUE THREAD

**Issue by umangachapagain** [gluster/gluster-mixins#5]
Volume status
Brick status

**Comment by cloudbehl** [comment]
> Volume status
> Brick status
> Volume IO Performance ( Optimal/Sub-optimal)
> Brick IO Performance ( Optimal/Sub-optimal)

@umangachapagain These 4 are done.

**Comment by umangachapagain** [comment]
> Volume status
> Brick status

Done
> Volume IO Performance ( Optimal/Sub-optimal)
> Brick IO Performance ( Optimal/Sub-optimal)

Not Feasible as discussed.
> Storage Device status (healthy/degraded)
> Tracked modules running status
> Tracked processes running status

Needs to come from operator and should be tracked separately.

**Comment by cloudbehl** [comment]
> > Volume status
> > Brick status
> 
> Done

@umangachapagain definition of Done should be when the PR is merged.  I still see an open PR. Please reopen or create a new one for brick and volume status.

**Comment by umangachapagain** [comment]
Merged.
